/*

		CITD_EDW_ROLE_Management_EDW_V2.0.sql
		
		created:	20230706	Andy Rupp
					initial release
					generated from CITD_EDW_ROLE_Management.xlsx
		updated:
		
*/

USE WAREHOUSE  COMPUTE_WH  ;

USE ROLE  SYSADMIN  ;
CREATE DATABASE CITD_D1_DEV  ;
CREATE SCHEMA  S1_LND  ;
CREATE SCHEMA  S2_INT  ;
CREATE SCHEMA  S3_SEM  ;

GRANT CREATE TABLE, MODIFY, MONITOR, REFERENCE_USAGE, USAGE ON FUTURE TABLES IN SCHEMA CITD_D1_DEV.S1_LND TO ROLE ADM_BI_SX  ;
GRANT USAGE ON FUTURE TABLES IN SCHEMA  CITD_D1_DEV.S1_LND TO ROLE ADM_DATA  ;
GRANT CREATE TABLE, MODIFY, MONITOR, REFERENCE_USAGE, USAGE ON FUTURE TABLES IN SCHEMA  CITD_D1_DEV.S1_LND TO ROLE ADM_DE_SX  ;
GRANT USAGE ON FUTURE TABLES IN SCHEMA  CITD_D1_DEV.S1_LND TO ROLE ADM_MASK  ;
GRANT USAGE, MASKING POLICY ON FUTURE TABLES IN SCHEMA  CITD_D1_DEV.S1_LND TO ROLE ADM_MON  ;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CITD_D1_DEV.S1_LND TO ROLE  DEV_BI_D1 ;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CITD_D1_DEV.S1_LND TO ROLE  DEV_DE_D1 ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CITD_D1_DEV.S2_INT  TO ROLE  DEV_BI_D1 ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CITD_D1_DEV.S2_INT  TO ROLE  DEV_DE_D1 ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CITD_D1_DEV.S3_SEM  TO ROLE  DEV_BI_D1 ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CITD_D1_DEV.S3_SEM  TO ROLE  DEV_DE_D1 ;

USE ROLE SECURITYADMIN ;
GRANT ROLE  ADM_BI_SX  TO USER ANDYRUPP ;
GRANT ROLE  ADM_BI_SX  TO USER EBERDICHESKY ;
GRANT ROLE  ADM_BI_SX  TO USER MSELVA ;
GRANT ROLE  ADM_DATA  TO USER OKHANOUTIN ;
GRANT ROLE  ADM_DE_SX  TO USER ANDYRUPP ;
GRANT ROLE  ADM_DE_SX  TO USER INFORMATICAUSER ;
GRANT ROLE  ADM_DE_SX  TO USER INFORMATICAUSERPRD ;
GRANT ROLE  ADM_DE_SX  TO USER MSELVA ;
GRANT ROLE  ADM_MASK  TO USER ANDYRUPP ;
GRANT ROLE  ADM_MASK  TO USER MSELVA ;

GRANT ROLE  DEV_BI_D1  TO USER ANDYRUPP ;
GRANT ROLE  DEV_BI_D1  TO USER CREN ;
GRANT ROLE  DEV_BI_D1  TO USER DOMOCONNECT ;
GRANT ROLE  DEV_BI_D1  TO USER EBERDICHESKY ;
GRANT ROLE  DEV_BI_D1  TO USER MSELVA ;
GRANT ROLE  DEV_BI_D1  TO USER NPANJABI ;
GRANT ROLE  DEV_BI_D1  TO USER SHUBHAM ;
GRANT ROLE  DEV_DE_D1  TO USER ANDYRUPP ;
GRANT ROLE  DEV_DE_D1  TO USER INFORMATICAUSER ;
GRANT ROLE  DEV_DE_D1  TO USER JGHADIGAONKAR ;
GRANT ROLE  DEV_DE_D1  TO USER MSELVA ;
GRANT ROLE  DEV_DE_D1  TO USER TPAREKH ;

USE ROLE  SYSADMIN  ;
CREATE DATABASE CITD_D2_TST  ;
CREATE SCHEMA  S1_LND  ;
CREATE SCHEMA  S2_INT  ;
CREATE SCHEMA  S3_SEM  ;

GRANT CREATE TABLE, MODIFY, MONITOR, REFERENCE_USAGE, USAGE ON FUTURE TABLES IN SCHEMA CITD_D2_TST.S1_LND TO ROLE  ADM_BI_SX  ;
GRANT USAGE ON FUTURE TABLES IN SCHEMA  CITD_D2_TST.S1_LND TO ROLE  ADM_DATA  ;
GRANT CREATE TABLE, MODIFY, MONITOR, REFERENCE_USAGE, USAGE ON FUTURE TABLES IN SCHEMA  CITD_D2_TST.S1_LND TO ROLE  ADM_DE_SX  ;
GRANT USAGE ON FUTURE TABLES IN SCHEMA  CITD_D2_TST.S1_LND TO ROLE  ADM_MASK  ;
GRANT USAGE, MASKING POLICY ON FUTURE TABLES IN SCHEMA  CITD_D2_TST.S1_LND TO ROLE  ADM_MON  ;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CITD_D2_TST.S1_LND TO ROLE  TST_BI_D2  ;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CITD_D2_TST.S1_LND TO ROLE  TST_DE_D2  ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CITD_D2_TST.S2_INT  TO ROLE  TST_BI_D2  ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CITD_D2_TST.S2_INT  TO ROLE  TST_DE_D2  ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CITD_D2_TST.S3_SEM  TO ROLE  TST_BI_D2  ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CITD_D2_TST.S3_SEM  TO ROLE  TST_DE_D2  ;

USE ROLE SECURITYADMIN ;
GRANT ROLE  TST_BI_D2  TO USER ANDYRUPP ;
GRANT ROLE  TST_BI_D2  TO USER CREN ;
GRANT ROLE  TST_BI_D2  TO USER DOMOCONNECT ;
GRANT ROLE  TST_BI_D2  TO USER EBERDICHESKY ;
GRANT ROLE  TST_BI_D2  TO USER MSELVA ;
GRANT ROLE  TST_BI_D2  TO USER NPANJABI ;
GRANT ROLE  TST_BI_D2  TO USER SHUBHAM ;
GRANT ROLE  TST_DE_D2  TO USER ANDYRUPP ;
GRANT ROLE  TST_DE_D2  TO USER INFORMATICAUSER ;
GRANT ROLE  TST_DE_D2  TO USER JGHADIGAONKAR ;
GRANT ROLE  TST_DE_D2  TO USER MSELVA ;
GRANT ROLE  TST_DE_D2  TO USER TPAREKH ;

USE ROLE  SYSADMIN  ;
CREATE DATABASE CITD_D3_PRD  ;
CREATE SCHEMA  S1_LND  ;
CREATE SCHEMA  S2_INT  ;
CREATE SCHEMA  S3_SEM  ;

GRANT CREATE TABLE, MODIFY, MONITOR, REFERENCE_USAGE, USAGE ON FUTURE TABLES IN SCHEMA CITD_D3_PRD.S1_LND TO ROLE  ADM_BI_SX  ;
GRANT USAGE ON FUTURE TABLES IN SCHEMA  CITD_D3_PRD.S1_LND TO ROLE  ADM_DATA  ;
GRANT CREATE TABLE, MODIFY, MONITOR, REFERENCE_USAGE, USAGE ON FUTURE TABLES IN SCHEMA  CITD_D3_PRD.S1_LND TO ROLE  ADM_DE_SX  ;
GRANT USAGE ON FUTURE TABLES IN SCHEMA  CITD_D3_PRD.S1_LND TO ROLE  ADM_MASK  ;
GRANT USAGE, MASKING POLICY ON FUTURE TABLES IN SCHEMA  CITD_D3_PRD.S1_LND TO ROLE  ADM_MON  ;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CITD_D3_PRD.S1_LND TO ROLE  USR_BI_D3  ;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CITD_D3_PRD.S1_LND TO ROLE  USR_DE_D3  ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CITD_D3_PRD.S2_INT  TO ROLE  USR_BI_D3  ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CITD_D3_PRD.S2_INT  TO ROLE  USR_DE_D3  ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CITD_D3_PRD.S3_SEM  TO ROLE  USR_BI_D3  ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CITD_D3_PRD.S3_SEM  TO ROLE  USR_DE_D3  ;

USE ROLE SECURITYADMIN
GRANT ROLE  USR_BI_D3  TO USER ANDYRUPP ;
GRANT ROLE  USR_BI_D3  TO USER CREN ;
GRANT ROLE  USR_BI_D3  TO USER DOMOCONNECT ;
GRANT ROLE  USR_BI_D3  TO USER EBERDICHESKY ;
GRANT ROLE  USR_BI_D3  TO USER MSELVA ;
GRANT ROLE  USR_BI_D3  TO USER NPANJABI ;
GRANT ROLE  USR_BI_D3  TO USER SHUBHAM ;
GRANT ROLE  USR_DE_D3  TO USER ANDYRUPP ;
GRANT ROLE  USR_DE_D3  TO USER INFORMATICAUSER ;
GRANT ROLE  USR_DE_D3  TO USER JGHADIGAONKAR ;
GRANT ROLE  USR_DE_D3  TO USER MSELVA ;
GRANT ROLE  USR_DE_D3  TO USER TPAREKH ;
